import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Gallery from '../components/sections/Gallery'
import News from '../components/sections/News'
import Navigation from '../components/sections/Navigation'
import Degree from '../components/sections/Degree'
import Numbers from '../components/sections/Numbers'
import Posts from '../components/sections/Posts'
import Giving from '../components/sections/Giving'
import Prefooter from '../components/sections/Prefooter'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>The Entrepreneurial University</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Gallery/>
        <News/>
        <Navigation/>
        <Degree/>
        <Posts/>
        <Giving/>
        <Prefooter/>
      </main>
    </>
  )
}
